-- 계층형 샘플 데이터 
CREATE TABLE T_MENU
(
	MENU_CD 	NUMBER 			NOT NULL,
	PARENT_CD 	NUMBER			NULL,
	MENU_NM 	VARCHAR2(100) 	NOT NULL
);

ALTER TABLE T_MENU
	ADD CONSTRAINT PK_T_MENU PRIMARY KEY (MENU_CD)
;

INSERT INTO T_MENU VALUES ( 101, NULL, 'R');

INSERT INTO T_MENU VALUES (102, 101, 'AA');
INSERT INTO T_MENU VALUES (103, 101, 'BB');
INSERT INTO T_MENU VALUES (104, 101, 'CC');

INSERT INTO T_MENU VALUES (105, 102, 'AA-1');
INSERT INTO T_MENU VALUES (106, 103, 'BB-1');
INSERT INTO T_MENU VALUES (107, 103, 'BB-2');
INSERT INTO T_MENU VALUES (108, 105, 'AA-1-1');
INSERT INTO T_MENU VALUES (109, 106, 'BB-1-1');
INSERT INTO T_MENU VALUES (100, 106, 'BB-1-1');
INSERT INTO T_MENU VALUES (111, 104, 'CC-1');

COMMIT;

-- 계층형 쿼리 (오라클 전용)
-- 실행 순서는 START WITH, CONNECT BY, WHERE 절 순임
-- title: 계층형 쿼리 (오라클 전용)
SELECT
	LEVEL AS LV
	, MENU_CD
	, PARENT_CD
	, MENU_NM
    , SUBSTR(SYS_CONNECT_BY_PATH(MENU_NM, ' > '), 4) AS MENU_PATH
	, CONNECT_BY_ROOT MENU_NM AS ROOT_NM
	, CONNECT_BY_ISLEAF AS ISLEAF
FROM T_MENU
START WITH PARENT_CD IS NULL -- 최상위 노드
CONNECT BY PRIOR MENU_CD = PARENT_CD -- 무모노드와 자식노드 연결
ORDER SIBLINGS BY MENU_NM -- 정렬
;

-- 계층형 쿼리 (재귀 사용)
-- title: 계층형 쿼리 (재귀 사용)
WITH RECURSIVE_MENU (
    LV
	, MENU_CD
    , PARENT_CD
    , MENU_NM
	, MENU_PATH
    , ROOT_NM
    , ISLEAF
) AS (
	SELECT
	    1 AS LV
		, MENU_CD
		, PARENT_CD
		, MENU_NM
		, MENU_NM AS MENU_PATH
		, MENU_NM AS ROOT_NM
		, 0 AS ISLEAF
	FROM T_MENU
	WHERE PARENT_CD IS NULL

	UNION ALL

    SELECT
    	RM.LV + 1
		, TM.MENU_CD
		, TM.PARENT_CD
		, TM.MENU_NM
		, RM.MENU_PATH || ' > ' || TM.MENU_NM AS MENU_PATH
		, RM.ROOT_NM
    	, CASE
    		WHEN (SELECT COUNT(MENU_CD) FROM T_MENU M WHERE M.PARENT_CD = TM.MENU_CD) > 0
    		THEN 0
    		ELSE 1
    	END AS ISLEAF
    FROM T_MENU TM
	INNER JOIN RECURSIVE_MENU RM ON RM.MENU_CD = TM.PARENT_CD
)
SELECT
	LV
	, MENU_CD
	, PARENT_CD
	, MENU_NM
	, MENU_PATH
	, ROOT_NM
	, ISLEAF
FROM RECURSIVE_MENU
ORDER BY MENU_PATH, MENU_CD
;