-- 고객, 아이템 유형별 주문금액 구하기, WITH 이용
WITH T_CUS_ITM_AMT AS (
	SELECT
		O.CUS_ID
	 	, MI.ITM_TP
	 	, SUM(TOD.UNT_PRC * TOD.ORD_QTY) AS ORD_AMT
	FROM T_ORD O
		INNER JOIN T_ORD_DET TOD ON TOD.ORD_SEQ = O.ORD_SEQ
		INNER JOIN M_ITM MI ON MI.ITM_ID = TOD.ITM_ID
	WHERE O.ORD_DT >= TO_DATE('20170201', 'YYYYMMDD')
	AND O.ORD_DT < TO_DATE('20170301', 'YYYYMMDD')
	GROUP BY O.CUS_ID, MI.ITM_TP
)
SELECT
	TCIA.CUS_ID
	, MC.CUS_NM
	, TCIA.ITM_TP
	, (
	    SELECT CBC.BAS_CD_NM
	    FROM C_BAS_CD CBC
		WHERE CBC.BAS_CD = TCIA.ITM_TP
	    AND CBC.BAS_CD_DV = 'ITM_TP'
	    AND CBC.LNG_CD = 'KO'
	) AS ITM_TP_NM
	, TCIA.ORD_AMT
FROM T_CUS_ITM_AMT TCIA
	INNER JOIN M_CUS MC ON TCIA.CUS_ID = MC.CUS_ID
ORDER BY TCIA.CUS_ID, TCIA.ITM_TP
;

-- 고객, 아이템별 주문금액 구하기, 전체주문 대비 주문금액비율 추가, WITH 이용
WITH T_CUS_ITM_AMT AS (
	SELECT
		O.CUS_ID
		 , MI.ITM_TP
		 , SUM(TOD.UNT_PRC * TOD.ORD_QTY) AS ORD_AMT
	FROM T_ORD O
		INNER JOIN T_ORD_DET TOD ON TOD.ORD_SEQ = O.ORD_SEQ
		INNER JOIN M_ITM MI ON MI.ITM_ID = TOD.ITM_ID
	WHERE O.ORD_DT >= TO_DATE('20170201', 'YYYYMMDD')
	  AND O.ORD_DT < TO_DATE('20170301', 'YYYYMMDD')
	GROUP BY O.CUS_ID, MI.ITM_TP
),
T_TTL_AMT AS (
    SELECT SUM(TCIA.ORD_AMT) AS ORD_AMT
    FROM T_CUS_ITM_AMT TCIA
)
SELECT
	TCIA.CUS_ID
	, MC.CUS_NM
	, TCIA.ITM_TP
	, (
		SELECT CBC.BAS_CD_NM
		FROM C_BAS_CD CBC
		WHERE CBC.BAS_CD = TCIA.ITM_TP
		AND CBC.BAS_CD_DV = 'ITM_TP'
	   	AND CBC.LNG_CD = 'KO'
	) AS ITM_TP_NM
	, TCIA.ORD_AMT
	, TO_CHAR(ROUND(TCIA.ORD_AMT / TTA.ORD_AMT * 100, 2)) || '%' AS ORD_AMT_RT
FROM T_CUS_ITM_AMT TCIA
	INNER JOIN M_CUS MC ON TCIA.CUS_ID = MC.CUS_ID
	, T_TTL_AMT TTA
ORDER BY ROUND(TCIA.ORD_AMT / TTA.ORD_AMT * 100, 2) DESC
;